stages:
  - test
  - deploy

test:
  stage: test
  image: python:3.8.7-slim-buster
  before_script:
    - python -m pip install --upgrade pip
    - pip install pytest certifi
    - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - python setup.py install
    # reduce the default SSL security level to get around a misconfiguration in the Ensembl server
    # https://github.com/Ensembl/ensembl-rest/issues/427
    # See https://askubuntu.com/a/1233456
    - sed -i 's/DEFAULT@SECLEVEL=2/DEFAULT@SECLEVEL=1/' /usr/lib/ssl/openssl.cnf
  script:
    - PYTHONPATH=. pytest tests
  environment:
    name: test-env
  only:
    - external_pull_requests
    - tags
    - main


# Not executed, parent job definition
.deploy-python-tool:
  stage: deploy
  image: python:3.8.7-slim-buster
  environment:
    name: $ENVIRONMENT_NAME
  script:
    # Start ssh-agent and set identity then run deploy script
    # See https://docs.gitlab.com/ee/ci/ssh_keys/
    - apt-get update
    - apt-get -y install openssh-client
    - eval "$(ssh-agent)"
    - echo "$EVA_ETL_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${CLUSTER_USER}@${CLUSTER_LOGIN_NODE_CODON} "${EVA_SOFTWARE_PATH_CODON}/eva-ebi-search-export/${ENVIRONMENT_NAME}_deployments/deploy.sh ${DEPLOY_POINT}"
  dependencies:
    - test

deploy-python-tool-development:
  extends: .deploy-python-tool
  variables:
    ENVIRONMENT_NAME: development
    DEPLOY_POINT: $CI_COMMIT_BRANCH
  only:
    - external_pull_requests
    - main

deploy-python-tool-production:
  extends: .deploy-python-tool
  when: manual
  variables:
    ENVIRONMENT_NAME: production
    DEPLOY_POINT: $CI_COMMIT_TAG
  only:
    - tags
